Todo list structure
SanaTameem/To-do-List pull request #2
Opened 2023-06-08 10:24 UTC by SanaTameem

I Set up a new Webpack project based on the Webpack exercise :
- I created an index.html file and created an empty To Do List placeholder `<div>`. 
- The index.html file is set as a template using the HTML Webpack Plugin.
- I created an index.js file and set an array of some simple to-do tasks (array of objects).
- Each task object is containing three keys:
  - description [string].
  - completed [bool].
  - index: [number].
- I have written a function to iterate over the tasks array and populate an HTML list item element for each task.
- The list is appearing in order of the index values for each task.
- I have created a style.css and set rules for the To-Do List.
  - CSS is loaded by Webpack Style/CSS Loader. 
- All source files (index.html, index.js and index.css) is located in` /src` directory and your distribution files will be generated by Webpack and served by Webpack dev server from `/dist ` folder.

2023-06-08 10:56 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @SanaTameem , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media0.giphy.com/media/7SF5scGB2AFrgsXP63/giphy.gif"/> |

## Highlights

- [ ].. ✅ Great code 
- [ ].. ✅ Highly motivated student
- [ ].. ✅ Green linters

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 10:56 UTC, joskalenda commented on src/index.js
> +  const index = new Date().getTime().toString();
- [ ] I like what you have accomplished, but you have done BEYOND the requirement @SanaTameem, what you did is for the next milestone `add and remove` if I remember fine, but for now, you are asked to create a static array of tasks and render it on page load(dynamically).

<img width="1062" alt="1" src="https://github.com/SanaTameem/To-do-List/assets/77843050/399acd2b-c698-4d54-9e89-9cb16d17f607">

- [ ] Ang again, you should not use a class constructor, but a function instead, if I were you, I think I should create a new branch in this same pr and make my changes not to break the actual code to meet the project requirement, please make sure you re-read again the project requirements before.

2023-06-08 14:43 UTC, bellom approved these changes
@SanaTameem,

### This is a manual review

# Approved :+1:

Great job working on the previously requested changes 🚀 

Cheers and Happy coding!:clap::clap::clap:

2023-06-08 14:44 UTC, bellom commented
It would be approved on your dashboard as soon as possible.

2023-06-10 09:17 UTC, Strangeal requested changes
Hi @SanaTameem, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)
## Highlights
Correct use of GitHub Flow ✅
Well-structured files ✅
All linter checks are passing ✅
Descriptive PR title with a great summary ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 09:17 UTC, Strangeal commented on src/index.js
> +};
- [ ] Impressive work display the list of the task as pointed out by the previous reviewer. It would be better if you `sort` the list of tasks based on their index before displaying it on the UI as specified in the project requirement. This will help sort your task to display orderly without having to worry about ordering them in your array. 
 - Example: If you have a list of tasks in an array with index such as 
`index: 10, index: 12, index: 5, index: 7` The sort method will sort the index like 
`eg: index: 5, index: 7, index: 10, index:12` 
See below for more details on project requirements:
<img width="996" alt="Screenshot 2023-06-07 at 15 15 43" src="https://github.com/Innocent259/Todo-List/assets/107192076/ded13da6-12fb-4d6d-b89d-764fc5f6c6b2">

- [ ]  To display the task in order of their `index` you can use the `sort()`  method.  You can sort the task above the iterate-task function before looping through.
  **Example:** `task.sort((a, b) => a.index - b.index)`

2023-06-10 09:57 UTC, merged